---
- hosts: ansible
  
  tasks:
  - name: Stop existing container 
    command: docker stop regapp-instance
    ignore_errors: yes

  - name: remove  existing container
    command: docker rm regapp-instance
    ignore_errors: yes
  
  - name: remove image
    command: docker rmi regapp:latest
    ignore_errors: yes
  - name: Create Docker Image from Recived artiacts from JENKINS
    command: docker build -t regapp:latest .
    args:
      chdir: /opt/ansible-jenkins-artif
  - name: Create Container 
    command: docker run -d --name regapp-instance -p 8998:8080 regapp:latest
